<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CPMM2067.Core\CPMM2067.Core.csproj" />
    <ProjectReference Include="..\CPMM2067.GameDetect\CPMM2067.GameDetect.csproj" />
    <ProjectReference Include="..\CPMM2067.Frameworks\CPMM2067.Frameworks.csproj" />
    <ProjectReference Include="..\CPMM2067.Diagnostics\CPMM2067.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
